name: Deploy SecurePass User App

on:
  push:
    branches:
      - main  # Change to your main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend Image
      uses: docker/build-push-action@v5
      with:
        context: ./backend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/securepass-user-be:latest

    - name: Build and Push Frontend Image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/securepass-user-fe:latest

    - name: Test SSH Connection
      run: |
        nc -zv ${{ secrets.SERVER_IP }} 22 || echo "SSH is not reachable"        
        
    - name: Deploy to Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_IP }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd /home/${{ secrets.SERVER_USER }}/ci_cd_testing
          docker compose down
          docker pull ${{ secrets.DOCKER_USERNAME }}/securepass-user-be:latest
          docker pull ${{ secrets.DOCKER_USERNAME }}/securepass-user-fe:latest
          docker compose up -d
